using System.Globalization;
using System.Text;
using EchoForge.Contracts.Library;
using EchoForge.Contracts.Summaries;

namespace EchoForge.Core.Exports;

/// <summary>What a summary export is written as.</summary>
public enum SummaryExportFormat
{
    /// <summary>The canonical revision, copied byte for byte.</summary>
    Json,

    /// <summary>Readable plain text.</summary>
    Text,

    /// <summary>Markdown, for pasting into somewhere that renders it.</summary>
    Markdown,
}

/// <summary>
/// Writes an activated summary revision out.
///
/// <para>
/// Built on the same three rules as the transcript exporter, for the same reasons. It is
/// <b>deterministic</b>: invariant formatting and one fixed line ending, so the same revision
/// exports to the same bytes twice. It is <b>additive</b>: it reads a canonical revision and
/// writes elsewhere, so a failed export cannot damage what it read. And canonical JSON is
/// <b>copied rather than re-serialised</b>, because re-rendering could change key order or number
/// formatting and the file would stop hashing to the digest it was activated under.
/// </para>
///
/// <para>
/// One rule is specific to summaries: <b>every claim is exported with its evidence</b>. A summary
/// stripped of its citations reads as a set of assertions from nowhere, which is precisely the
/// thing the whole evidence model exists to prevent. Owner and date statuses travel with it too,
/// so an unknown owner stays visibly unknown in a document somebody pastes into an email.
/// </para>
/// </summary>
public static class SummaryExporter
{
    private const char NewLine = '\n';

    public static string Extension(SummaryExportFormat format) => format switch
    {
        SummaryExportFormat.Json => ".json",
        SummaryExportFormat.Text => ".txt",
        SummaryExportFormat.Markdown => ".md",
        _ => throw new ArgumentOutOfRangeException(nameof(format), format, "unknown summary export format"),
    };

    public static string Describe(SummaryExportFormat format) => format switch
    {
        SummaryExportFormat.Json => "Summary JSON (canonical)",
        SummaryExportFormat.Text => "Plain text",
        SummaryExportFormat.Markdown => "Markdown",
        _ => format.ToString(),
    };

    /// <summary>A file name that is safe on Windows and still recognisable.</summary>
    public static string SuggestFileName(SummaryDocument summary, SummaryExportFormat format)
    {
        ArgumentNullException.ThrowIfNull(summary);

        string stamp = summary.CreatedAtUtc.UtcDateTime.ToString("yyyyMMdd-HHmm", CultureInfo.InvariantCulture);
        string name = string.Create(
            CultureInfo.InvariantCulture,
            $"{summary.SessionId}-{stamp}-summary-v{summary.SummaryRevision}");

        return ExportNaming.Sanitize(name) + Extension(format);
    }

    /// <summary>Renders a summary. JSON is not produced here; it is copied by <see cref="Export"/>.</summary>
    public static string Render(
        SummaryDocument summary,
        SummaryExportFormat format,
        SpeakerAliases? aliases = null,
        string? title = null) => format switch
        {
            SummaryExportFormat.Markdown => RenderMarkdown(summary, aliases, title),
            SummaryExportFormat.Text => RenderText(summary, aliases, title),
            SummaryExportFormat.Json => throw new ArgumentOutOfRangeException(
                nameof(format), format, "canonical JSON is copied, never re-rendered"),
            _ => throw new ArgumentOutOfRangeException(nameof(format), format, "unknown summary export format"),
        };

    // -- markdown ---------------------------------------------------------------------------------

    private static string RenderMarkdown(SummaryDocument summary, SpeakerAliases? aliases, string? title)
    {
        StringBuilder markdown = new();

        Line(markdown, "# " + Escape(title ?? "Meeting summary"));
        Line(markdown, string.Empty);

        // Provenance first. A summary read without knowing what produced it, and from which
        // transcript, is a set of claims with no way to check them.
        Line(markdown, "> Generated by " + Escape(Describe(summary.Model)) + ".");
        Line(markdown, "> Summary version " + Invariant(summary.SummaryRevision)
            + ", from transcript version " + Invariant(summary.TranscriptRevision)
            + ", " + summary.CreatedAtUtc.UtcDateTime.ToString("u", CultureInfo.InvariantCulture) + ".");

        if (!summary.Model.ProducesSummaries)
        {
            Line(markdown, "> **This was produced by a deterministic placeholder.** It quotes and groups what was said "
                + "rather than understanding it, and is not a summary.");
        }

        if (summary.RepairAttempt > 0)
        {
            Line(markdown, "> The first attempt was not supported by the transcript and was refused, so it was generated again.");
        }

        Line(markdown, string.Empty);

        if (!string.IsNullOrWhiteSpace(summary.Overview))
        {
            Line(markdown, summary.Narrative is null && summary.Brief is null ? "## Overview" : "## Summary");
            Line(markdown, string.Empty);
            Line(markdown, Escape(summary.Overview));
            Line(markdown, string.Empty);
        }

        // A v3 document exports as the brief a person read: the plan, then the sections the meeting
        // earned. The structured facts underneath it are the audit view and stay below.
        if (summary.Brief is { } brief)
        {
            Plan(markdown, brief, aliases);

            NarrativeSection(markdown, "Decisions", brief.Decisions, aliases);
            NarrativeSection(markdown, "Blockers and dependencies", brief.Blockers, aliases);
            NarrativeSection(markdown, "Important context", brief.ImportantContext, aliases);
            NarrativeSection(markdown, "Follow-ups", brief.FollowUps, aliases);
            NarrativeSection(markdown, "Open questions", brief.OpenQuestions, aliases);
            NarrativeSection(markdown, "Discussed, not now", brief.Backlog, aliases);
            NarrativeSection(markdown, "Risks", brief.Risks, aliases);

            Line(markdown, "## Supporting details");
            Line(markdown, string.Empty);
        }
        else if (summary.Narrative is { } narrative)
        {
            NarrativeSection(markdown, "Main topics", narrative.MainTopics, aliases);
            NarrativeSection(markdown, "Important details", narrative.ImportantDetails, aliases);
        }

        Section(markdown, "Key points", summary.KeyPoints, aliases);
        Section(markdown, "Decisions", summary.Decisions, aliases);
        Actions(markdown, summary.ActionItems, aliases);
        if (summary.Brief is null && summary.Narrative is { } grounded)
        {
            NarrativeSection(markdown, "Follow-ups", grounded.FollowUps, aliases);
        }
        Section(markdown, "Open questions", summary.OpenQuestions, aliases);
        Section(markdown, "Risks", summary.Risks, aliases);
        Section(markdown, "Blockers", summary.Blockers, aliases);
        Section(markdown, "Discussed, not now", summary.FutureIdeas, aliases);
        Section(markdown, "Important context", summary.ImportantContext, aliases);
        Section(markdown, "Dependencies", summary.Dependencies, aliases);

        return markdown.ToString();
    }

    /// <summary>
    /// The action plan, numbered, split by whose work it is.
    ///
    /// <para>
    /// An empty plan is written out as a sentence rather than omitted. "No post-meeting work was
    /// assigned" is a finding about the meeting; a missing heading is indistinguishable from an
    /// export that went wrong.
    /// </para>
    /// </summary>
    private static void Plan(StringBuilder markdown, MeetingBrief brief, SpeakerAliases? aliases)
    {
        Line(markdown, "## What you need to do");
        Line(markdown, string.Empty);

        MeetingPlanStep[] yours = [.. brief.YourSteps];
        MeetingPlanStep[] others = [.. brief.OtherPeoplesSteps];

        if (yours.Length == 0 && others.Length == 0)
        {
            Line(markdown, "No post-meeting work was assigned in this meeting.");
            Line(markdown, string.Empty);
            return;
        }

        int number = 0;
        foreach (MeetingPlanStep step in yours)
        {
            Step(markdown, ++number, step, aliases);
        }

        Line(markdown, string.Empty);

        if (others.Length > 0)
        {
            Line(markdown, "## Other people's action items");
            Line(markdown, string.Empty);

            foreach (MeetingPlanStep step in others)
            {
                Step(markdown, ++number, step, aliases);
            }

            Line(markdown, string.Empty);
        }
    }

    private static void Step(StringBuilder markdown, int number, MeetingPlanStep step, SpeakerAliases? aliases)
    {
        Line(markdown, number.ToString(CultureInfo.InvariantCulture) + ". **" + Escape(step.Title) + "**"
            + Citations(step.Evidence, aliases));

        if (!string.IsNullOrWhiteSpace(step.Detail))
        {
            Line(markdown, "   " + Escape(step.Detail));
        }

        List<string> notes = [];
        if (!string.IsNullOrWhiteSpace(step.Owner))
        {
            notes.Add("owner " + Escape(step.Owner));
        }
        if (step.DueDate is { } date)
        {
            notes.Add("due " + date);
        }
        else if (!string.IsNullOrWhiteSpace(step.DueDateText))
        {
            notes.Add("due " + Escape(step.DueDateText));
        }
        if (!string.IsNullOrWhiteSpace(step.DependsOn))
        {
            notes.Add("waits on " + Escape(step.DependsOn));
        }

        // Said only when the ordering is EchoForge's reasoning rather than the meeting's words.
        if (step.Support != PlanBasis.Explicit)
        {
            notes.Add(step.Support == PlanBasis.GroundedInference
                ? "follows from what was said"
                : "suggested order");
        }

        if (notes.Count > 0)
        {
            Line(markdown, "   _" + string.Join(" · ", notes) + "_");
        }
    }

    private static void NarrativeSection(
        StringBuilder markdown,
        string heading,
        IReadOnlyList<SummaryNarrativeBlock> blocks,
        SpeakerAliases? aliases)
    {
        if (blocks.Count == 0)
        {
            return;
        }

        Line(markdown, "## " + heading);
        Line(markdown, string.Empty);
        foreach (SummaryNarrativeBlock block in blocks)
        {
            Line(markdown, "- " + Escape(block.Text) + Citations(block.Evidence, aliases));
        }

        Line(markdown, string.Empty);
    }

    private static void Section(StringBuilder markdown, string heading, IReadOnlyList<SummaryItem> items, SpeakerAliases? aliases)
    {
        if (items.Count == 0)
        {
            return;
        }

        Line(markdown, "## " + heading);
        Line(markdown, string.Empty);

        foreach (SummaryItem item in items)
        {
            Line(markdown, "- " + Escape(item.Text) + Certainty(item.Certainty) + Citations(item.Evidence, aliases));
        }

        Line(markdown, string.Empty);
    }

    private static void Actions(StringBuilder markdown, IReadOnlyList<SummaryAction> actions, SpeakerAliases? aliases)
    {
        if (actions.Count == 0)
        {
            return;
        }

        Line(markdown, "## Action items");
        Line(markdown, string.Empty);

        foreach (SummaryAction action in actions)
        {
            // Owner and date carry their status into the document. "Owner: unknown" is a real
            // answer, and an exported action that simply omitted it would read as though nobody
            // had thought about who was doing the work.
            string owner = action.Owner is { } named
                ? "Owner: " + Escape(named) + (action.OwnerSupport == SupportStatus.Inferred ? " (inferred)" : string.Empty)
                : "Owner: unknown";

            string due = action.DueDate is { } date
                ? "Due: " + Escape(date) + (action.DueDateSupport == SupportStatus.Inferred ? " (inferred)" : string.Empty)
                : action.DueDateText is { } wording
                    ? "Due: unknown (\"" + Escape(wording) + "\")"
                    : "Due: unknown";

            Line(markdown, "- " + Escape(action.Task) + Certainty(action.Certainty) + Citations(action.Evidence, aliases));
            Line(markdown, "  - " + owner);
            Line(markdown, "  - " + due);
        }

        Line(markdown, string.Empty);
    }

    private static string Certainty(string certainty) =>
        string.Equals(certainty, SupportStatuses.Inferred, StringComparison.Ordinal) ? " *(inferred)*" : string.Empty;

    /// <summary>Citations as timestamps, with the revision they belong to.</summary>
    private static string Citations(IReadOnlyList<SummaryEvidence> evidence, SpeakerAliases? aliases)
    {
        if (evidence.Count == 0)
        {
            return string.Empty;
        }

        IEnumerable<string> references = evidence.Select(e =>
        {
            string speaker = aliases?.Present(SpeakerIdFor(e.SourceTrack), NameFor(e.SourceTrack)) ?? NameFor(e.SourceTrack);
            return e.DisplayTimestamp + " " + speaker;
        });

        return " — [" + Escape(string.Join("; ", references)) + "]";
    }

    private static string SpeakerIdFor(string sourceTrack) =>
        string.Equals(sourceTrack, "microphone", StringComparison.Ordinal) ? "speaker-you" : "speaker-remote";

    private static string NameFor(string sourceTrack) =>
        string.Equals(sourceTrack, "microphone", StringComparison.Ordinal) ? "You" : "Remote";

    /// <summary>
    /// Escapes the characters that would otherwise turn meeting text into formatting.
    ///
    /// <para>
    /// A transcript can contain anything somebody said, including asterisks, underscores,
    /// backticks and brackets. Left raw, a decision containing <c>*</c> silently becomes italic
    /// and a line starting with <c>#</c> becomes a heading — the exported document then says
    /// something slightly different from the summary it came from.
    /// </para>
    /// </summary>
    public static string Escape(string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return string.Empty;
        }

        StringBuilder escaped = new(text.Length + 8);
        bool atStart = true;

        foreach (char character in text)
        {
            // Significant wherever they appear: these turn text into emphasis, code or a link.
            bool always = character is '\\' or '`' or '*' or '_' or '[' or ']' or '<' or '>' or '|';

            // Significant only at the start of a line, where they would begin a heading, a list
            // or a quote. Escaping these everywhere is what turns a model id like gemma-4-12b
            // into gemma\-4\-12b for no benefit: a hyphen mid-sentence is just a hyphen.
            bool structural = atStart && character is '#' or '-' or '+' or '=';

            if (always || structural)
            {
                escaped.Append('\\');
            }

            // Newlines inside one item would break the list structure it sits in.
            escaped.Append(character is '\r' or '\n' ? ' ' : character);

            atStart = false;
        }

        return escaped.ToString();
    }

    // -- plain text -------------------------------------------------------------------------------

    private static string RenderText(SummaryDocument summary, SpeakerAliases? aliases, string? title)
    {
        StringBuilder text = new();

        Line(text, title ?? "Meeting summary");
        Line(text, new string('=', (title ?? "Meeting summary").Length));
        Line(text, string.Empty);
        Line(text, Describe(summary.Model));
        Line(text, "Summary version " + Invariant(summary.SummaryRevision)
            + ", from transcript version " + Invariant(summary.TranscriptRevision));
        Line(text, summary.CreatedAtUtc.UtcDateTime.ToString("u", CultureInfo.InvariantCulture));

        if (!summary.Model.ProducesSummaries)
        {
            Line(text, "NOTE: produced by a deterministic placeholder. It is not a summary.");
        }

        Line(text, string.Empty);

        if (!string.IsNullOrWhiteSpace(summary.Overview))
        {
            Line(text, summary.Narrative is null ? "OVERVIEW" : "SUMMARY");
            Line(text, summary.Overview);
            Line(text, string.Empty);
        }

        if (summary.Narrative is { } narrative)
        {
            TextNarrativeSection(text, "MAIN TOPICS", narrative.MainTopics);
            TextNarrativeSection(text, "IMPORTANT DETAILS", narrative.ImportantDetails);
        }

        TextSection(text, "KEY POINTS", summary.KeyPoints);
        TextSection(text, "DECISIONS", summary.Decisions);

        if (summary.ActionItems.Count > 0)
        {
            Line(text, "ACTION ITEMS");
            foreach (SummaryAction action in summary.ActionItems)
            {
                Line(text, "  - " + action.Task + PlainCitations(action.Evidence));
                Line(text, "      owner: " + (action.Owner ?? "unknown"));
                Line(text, "      due:   " + (action.DueDate ?? action.DueDateText ?? "unknown"));
            }

            Line(text, string.Empty);
        }

        if (summary.Narrative is { } grounded)
        {
            TextNarrativeSection(text, "FOLLOW-UPS", grounded.FollowUps);
        }

        TextSection(text, "OPEN QUESTIONS", summary.OpenQuestions);
        TextSection(text, "RISKS", summary.Risks);
        TextSection(text, "BLOCKERS", summary.Blockers);

        _ = aliases;
        return text.ToString();
    }

    private static void TextNarrativeSection(
        StringBuilder text,
        string heading,
        IReadOnlyList<SummaryNarrativeBlock> blocks)
    {
        if (blocks.Count == 0)
        {
            return;
        }

        Line(text, heading);
        foreach (SummaryNarrativeBlock block in blocks)
        {
            Line(text, "  - " + block.Text + PlainCitations(block.Evidence));
        }

        Line(text, string.Empty);
    }

    private static void TextSection(StringBuilder text, string heading, IReadOnlyList<SummaryItem> items)
    {
        if (items.Count == 0)
        {
            return;
        }

        Line(text, heading);
        foreach (SummaryItem item in items)
        {
            Line(text, "  - " + item.Text + PlainCitations(item.Evidence));
        }

        Line(text, string.Empty);
    }

    private static string PlainCitations(IReadOnlyList<SummaryEvidence> evidence) =>
        evidence.Count == 0 ? string.Empty : "  [" + string.Join("; ", evidence.Select(e => e.DisplayTimestamp)) + "]";

    private static string Describe(SummaryModel model) =>
        model.Backend + " " + model.ModelId + (model.ProducesSummaries ? string.Empty : " (placeholder)");

    private static void Line(StringBuilder builder, string value) => builder.Append(value).Append(NewLine);

    private static string Invariant(int value) => value.ToString(CultureInfo.InvariantCulture);

    // -- writing ------------------------------------------------------------------------------------

    /// <summary>Writes an export. Never replaces an existing file unless told to.</summary>
    public static ExportResult Export(
        SummaryDocument summary,
        string? canonicalPath,
        SummaryExportFormat format,
        string destinationPath,
        bool overwrite = false,
        SpeakerAliases? aliases = null,
        string? title = null)
    {
        ArgumentNullException.ThrowIfNull(summary);
        ArgumentException.ThrowIfNullOrWhiteSpace(destinationPath);

        if (File.Exists(destinationPath) && !overwrite)
        {
            return ExportResult.Fail(
                "exists",
                "A file of that name is already there. Choose another name, or confirm replacing it.");
        }

        byte[] payload;

        if (format == SummaryExportFormat.Json)
        {
            if (canonicalPath is null || !File.Exists(canonicalPath))
            {
                return ExportResult.Fail("source_missing", "The summary file could not be found.");
            }

            try
            {
                payload = File.ReadAllBytes(canonicalPath);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                return ExportResult.Fail("source_unreadable", $"The summary could not be read ({ex.GetType().Name}).");
            }
        }
        else
        {
            payload = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false)
                .GetBytes(Render(summary, format, aliases, title));
        }

        return ExportNaming.WriteAtomically(destinationPath, payload, overwrite);
    }
}
