<#
.SYNOPSIS
    Regenerates the isolated Linux NeMo dependency lock.

.DESCRIPTION
    Resolves NeMo 2.7.3 and PyTorch 2.8.0+cu128 for Linux x86_64 / CPython 3.11 and records a
    complete hash set for every distribution. PyTorch packages are routed to the official cu128
    index by uv; ordinary dependencies retain uv's safe first-index behavior.

    This script downloads metadata only. It never installs packages or touches EchoForge data.

.PARAMETER Check
    Compare a fresh resolution with worker-nemo/requirements-production.txt without writing it.
#>
[CmdletBinding()]
param([switch] $Check)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$inputPath = Join-Path $repoRoot 'worker-nemo\requirements-production.in'
$lockPath = Join-Path $repoRoot 'worker-nemo\requirements-production.txt'
$temporary = [System.IO.Path]::GetTempFileName()

if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    Write-Host 'uv was not found on PATH.' -ForegroundColor Red
    exit 2
}

try {
    & uv pip compile $inputPath `
        --python-platform linux `
        --python-version 3.11 `
        --torch-backend cu128 `
        --generate-hashes `
        --no-header `
        --quiet `
        -o $temporary
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    $body = [System.IO.File]::ReadAllText($temporary, [System.Text.Encoding]::UTF8)
    $body = $body.TrimStart([char]0xFEFF).Replace("`r`n", "`n").TrimStart()
    $header = @(
        '# Generated by scripts/lock-nemo-runtime.ps1 for Linux x86_64 / CPython 3.11.'
        '# Every distribution is hash-pinned; inference never invokes this file or a package index.'
        '--extra-index-url https://download.pytorch.org/whl/cu128'
        ''
    ) -join "`n"
    $resolved = $header + "`n" + $body

    if ($Check) {
        if (-not (Test-Path -LiteralPath $lockPath)) {
            Write-Host 'The NeMo lock does not exist.' -ForegroundColor Red
            exit 1
        }

        $current = [System.IO.File]::ReadAllText($lockPath, [System.Text.Encoding]::UTF8)
        $current = $current.TrimStart([char]0xFEFF).Replace("`r`n", "`n")
        if ($current -ne $resolved) {
            Write-Host 'The committed NeMo lock does not match a fresh resolution.' -ForegroundColor Red
            exit 1
        }

        $packages = @($body -split "`n" | Where-Object { $_ -match '^[A-Za-z0-9_.-]+==' }).Count
        Write-Host "NeMo lock matches a fresh resolution ($packages packages)." -ForegroundColor Green
        exit 0
    }

    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllText($lockPath, $resolved, $utf8NoBom)
    Write-Host "Wrote $lockPath" -ForegroundColor Green
}
finally {
    Remove-Item -LiteralPath $temporary -Force -ErrorAction SilentlyContinue
}
