"""Regenerate the synthetic benchmark corpus.

Synthetic means written, not recorded. This meeting exists so the scorer has something to be
tested against; it is evidence about arithmetic and nothing else, and every meeting it produces
carries ``"synthetic": true`` so the validator refuses to let it sit in a development or release
corpus.

It is generated by a script rather than hand-edited so the transcript digest recorded in the
corpus is always the digest of the transcript actually on disk. A corpus whose digest has drifted
away from its transcript is exactly the sort of quiet inconsistency the separation checks exist to
catch, and it should not be possible to introduce one by editing a file.

    python scripts/make-synthetic-corpus.py
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "summary-benchmark" / "synthetic"

# The meeting is built to exercise the parts of scoring that are easy to get wrong: a decision
# that is later reversed, an action with a named owner and a resolvable date, an action nobody was
# assigned, an open question, and a topic that is discussed and explicitly deferred.
LINES: list[tuple[str, str]] = [
    ("You", "Right, let's settle the release date today."),
    ("Remote", "We will ship the beta on Friday."),
    ("You", "Agreed, Friday works for the beta."),
    ("Remote", "Alex will prepare the release notes by 2026-08-14."),
    ("You", "Who is going to handle the migration guide?"),
    ("Remote", "Someone will have to write it up, we can decide later."),
    ("You", "Hold on, support says Friday is bad for them."),
    ("Remote", "Fine, we will ship the beta on Monday instead."),
    ("You", "Should we also raise the price to ninety-nine dollars?"),
    ("Remote", "Let's not decide that now, it needs finance."),
    ("You", "One risk: the vendor has not confirmed the certificate yet."),
    ("Remote", "And we are blocked on their sandbox until they do."),
]


def segment(index: int, speaker: str, text: str) -> dict:
    microphone = speaker == "You"
    return {
        "id": f"segment-{index:06d}",
        "epoch": 1,
        "start_seconds": (index - 1) * 12.0,
        "end_seconds": (index - 1) * 12.0 + 10.0,
        "speaker_id": "speaker-you" if microphone else "speaker-remote",
        "speaker_name": "You" if microphone else "Remote",
        "source_track": "microphone" if microphone else "system",
        "text": text,
        "confidence": None,
        "language": "en",
        "words": [],
        "overlaps_segment_ids": [],
    }


def build_transcript() -> dict:
    segments = [segment(i, speaker, text) for i, (speaker, text) in enumerate(LINES, start=1)]
    return {
        "schema_version": 1,
        "session_id": "01JSYNTHETIC001",
        "transcript_revision": 1,
        "created_at_utc": "2026-08-07T12:00:00+00:00",
        "source_manifest_sha256": "a" * 64,
        "duration_seconds": 600.0,
        "model": {
            "runtime": "echoforge-synthetic", "backend": "written-by-hand", "model_id": "none",
            "revision": "none", "compute_type": "none", "recognizes_speech": False,
            "worker_version": "0.1.0",
        },
        "epochs": [{"index": 1, "start_seconds": 0.0, "end_seconds": 600.0}],
        "speakers": [
            {"id": "speaker-you", "name": "You", "source_track": "microphone"},
            {"id": "speaker-remote", "name": "Remote", "source_track": "system"},
        ],
        "languages": [{"source_track": "microphone", "code": "en", "probability": None}],
        "segments": segments,
    }


def build_corpus(transcript_digest: str) -> dict:
    return {
        "schema_version": 1,
        "corpus_id": "synthetic-v1",
        "kind": "synthetic",
        "created_utc": "2026-08-07T00:00:00+00:00",
        "notes": (
            "Written by hand to test the scorer. Not a recording, not annotated by anyone, and not "
            "evidence about any model's summary quality. Regenerate with scripts/make-synthetic-corpus.py."
        ),
        "match_threshold": 0.5,
        "meetings": [
            {
                "meeting_id": "synthetic-001",
                "meeting_date": "2026-08-07",
                "transcript_path": "transcripts/synthetic-001.json",
                "transcript_sha256": transcript_digest,
                "transcript_fidelity": "human_corrected",
                "synthetic": True,
                "annotator": "generated by scripts/make-synthetic-corpus.py",
                "notes": "Exercises a reversal, a named owner, a deliberate unknown, and a deferred topic.",
                "gold": {
                    "decisions": [
                        {
                            "id": "d1",
                            "text": "Ship the beta on Friday",
                            "evidence": ["segment-000002", "segment-000003"],
                            "aliases": [
                                "We will ship the beta on Friday",
                                "The beta ships on Friday",
                                "The beta will be shipped on Friday",
                                "The beta was agreed to be shipped on Friday",
                                "Beta release scheduled for Friday",
                            ],
                        },
                        {
                            "id": "d2",
                            "text": "Ship the beta on Monday instead",
                            "evidence": ["segment-000008"],
                            "aliases": [
                                "We will ship the beta on Monday instead",
                                "The beta will be shipped on Monday",
                                "The beta ships on Monday instead of Friday",
                                "Beta release moved to Monday",
                            ],
                            "notes": "Reverses d1. Both must survive; keeping only one hides that the meeting changed its mind.",
                        },
                    ],
                    "action_items": [
                        {
                            "id": "a1",
                            "task": "Prepare the release notes",
                            "evidence": ["segment-000004"],
                            "aliases": [
                                "Alex will prepare the release notes by 2026-08-14",
                                "Alex will prepare the release notes",
                                "Prepare the release notes by 2026-08-14",
                            ],
                            "owner": "Alex",
                            "owner_status": "explicit",
                            "due_date": "2026-08-14",
                            "due_date_status": "explicit",
                        },
                        {
                            "id": "a2",
                            "task": "Write up the migration guide",
                            "evidence": ["segment-000006"],
                            "aliases": [
                                "Someone will have to write up the migration guide",
                                "Write the migration guide",
                                "The migration guide needs to be written up",
                                "Migration guide still needs an owner",
                            ],
                            "owner": None,
                            "owner_status": "unknown",
                            "due_date": None,
                            "due_date_status": "unknown",
                            "notes": (
                                "Nobody was assigned. An owner here is an invented commitment, and 'Someone' "
                                "is not a name."
                            ),
                        },
                    ],
                    "key_points": [
                        {
                            "id": "k1",
                            "text": "The release date was the subject of the meeting",
                            "evidence": ["segment-000001"],
                            "aliases": [
                                "The meeting was called to settle the release date",
                                "The release date was discussed",
                                "Discussion about the release date for the beta",
                            ],
                        }
                    ],
                    "open_questions": [
                        {
                            "id": "q1",
                            "text": "Who will handle the migration guide?",
                            "evidence": ["segment-000005"],
                            "aliases": ["Who is going to handle the migration guide?"],
                        },
                        {
                            "id": "q2",
                            "text": "Whether to raise the price to ninety-nine dollars",
                            "evidence": ["segment-000009", "segment-000010"],
                            "notes": "Discussed and explicitly deferred. A summary that emits this as a decision is wrong.",
                        },
                    ],
                    "risks": [
                        {
                            "id": "r1",
                            "text": "The vendor has not confirmed the certificate",
                            "evidence": ["segment-000011"],
                        }
                    ],
                    "blockers": [
                        {
                            "id": "b1",
                            "text": "Blocked on the vendor's sandbox",
                            "evidence": ["segment-000012"],
                        }
                    ],
                    "contradictions": [
                        {
                            "id": "c1",
                            "item_ids": ["d1", "d2"],
                            "notes": "Friday was decided and then reversed to Monday.",
                        }
                    ],
                },
            }
        ],
    }


def main() -> int:
    transcripts = ROOT / "transcripts"
    transcripts.mkdir(parents=True, exist_ok=True)

    payload = json.dumps(build_transcript(), indent=2) + "\n"
    (transcripts / "synthetic-001.json").write_text(payload, encoding="utf-8")

    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    corpus = json.dumps(build_corpus(digest), indent=2) + "\n"
    (ROOT / "corpus.json").write_text(corpus, encoding="utf-8")

    print(f"transcript sha256: {digest}")
    print(f"written: {ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
