"""Regenerate the synthetic benchmark corpus.

Synthetic means written, not recorded. This meeting exists so the scorer has something to be
tested against; it is evidence about arithmetic and nothing else, and every meeting it produces
carries ``"synthetic": true`` so the validator refuses to let it sit in a development or release
corpus.

It is generated by a script rather than hand-edited so the transcript digest recorded in the
corpus is always the digest of the transcript actually on disk. A corpus whose digest has drifted
away from its transcript is exactly the sort of quiet inconsistency the separation checks exist to
catch, and it should not be possible to introduce one by editing a file.

    python scripts/make-synthetic-corpus.py
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "summary-benchmark" / "synthetic"

# The meeting is built to exercise the parts of scoring that are easy to get wrong: a decision
# that is later reversed, an action with a named owner and a resolvable date, an action nobody was
# assigned, an open question, and a topic that is discussed and explicitly deferred.
LINES: list[tuple[str, str]] = [
    ("You", "Right, let's settle the release date today."),
    ("Remote", "We will ship the beta on Friday."),
    ("You", "Agreed, Friday works for the beta."),
    ("Remote", "Alex will prepare the release notes by 2026-08-14."),
    ("You", "Who is going to handle the migration guide?"),
    ("Remote", "Someone will have to write it up, we can decide later."),
    ("You", "Hold on, support says Friday is bad for them."),
    ("Remote", "Fine, we will ship the beta on Monday instead."),
    ("You", "Should we also raise the price to ninety-nine dollars?"),
    ("Remote", "Let's not decide that now, it needs finance."),
    ("You", "One risk: the vendor has not confirmed the certificate yet."),
    ("Remote", "And we are blocked on their sandbox until they do."),
]



# A short recorder test. It exists because of a real failure: EchoForge summarised a call very like
# this one and produced "Stop the recording" as an action item, plus an observation about the
# interface getting smaller dressed up as work. Neither is post-meeting work, and a brief that says
# so is the correct answer. The gold expectation here is an **empty** action plan.
#
# Written, not transcribed. No real conversation is committed to this repository.
SHORT_TEST_LINES: list[tuple[str, str]] = [
    ("You", "Okay, I've started recording, can you hear me on your side?"),
    ("Remote", "Yeah, you're coming through clearly."),
    ("You", "Good. I mainly want to check that both tracks are being captured separately."),
    ("Remote", "It looks like it. One thing though, the window seems to be getting smaller as it goes."),
    ("You", "Yeah I noticed that too, the panel compacts itself while the recording runs."),
    ("Remote", "Not a problem, just something I noticed."),
    ("You", "Right, I think we've got what we need. Stop the recording."),
    ("Remote", "Stopping it now."),
]

# A long work meeting, written to contain every relationship the action plan has to get right: an
# immediate customer deadline, a missing access blocker, work that depends on that access, a second
# customer task behind it, speculative future ideas, an explicitly deferred task, an assignment for
# somebody else, a reversed decision, in-meeting instructions, and money talk that is important
# context rather than a task.
WORK_MEETING_LINES: list[tuple[str, str]] = [
    ("You", "Before anything else - I still don't have access to the Rebuild admin console."),
    ("Remote", "That's on me. I'll get you added to Rebuild today."),
    ("You", "I can't check which lead fields the live site is writing until I'm in there, and the JR integration is waiting on exactly that."),
    ("Remote", "Understood. Nothing downstream moves until you have it."),
    ("You", "The other thing is the demo. We're showing signup and onboarding to the customer tomorrow morning."),
    ("Remote", "Then QA signup, login and onboarding before that, please. That's the priority once you're unblocked."),
    ("You", "Will do. I'll write down anything I find in billing and the workspace switcher rather than fixing it on the spot."),
    ("Remote", "Good - document it, don't chase it. We can't have the demo slip because of a billing bug nobody asked about."),
    ("You", "Once the demo is done I'll finish JR's website integration and get them live."),
    ("Remote", "Yes. And once JR is working, write it up as a pattern so the next site is not a bespoke job."),
    ("You", "After that I can take over the ICH website lead pipeline."),
    ("Remote", "Let's share the screen for a second so you can see what I mean."),
    ("You", "Scroll down a bit - there, that's the field mapping."),
    ("Remote", "One warning: do not touch the existing Google Ads campaigns. They're producing leads and I don't want them disturbed."),
    ("You", "Understood, I'll leave the ads alone entirely."),
    ("You", "What about error monitoring? We still have nothing catching production exceptions."),
    ("Remote", "Worth doing, but not this week. Put it on the backlog."),
    ("You", "I was also thinking we could eventually build a proper customer portal, and maybe automate the whole onboarding sequence."),
    ("Remote", "Interesting, but that's a long way out. Park it."),
    ("You", "One more - should we move the shared inbox into a real helpdesk?"),
    ("Remote", "Let's keep Gmail for now and revisit it. I don't want it eating this week."),
    ("You", "On money - the JR contract is eleven thousand, and ICH is roughly double that if the pipeline works."),
    ("Remote", "Right, which is why JR going live matters more than any of the other ideas we just talked about."),
    ("Remote", "Actually, one correction - I said earlier we'd do the ICH pipeline after JR. Let's do the reusable pattern first, then ICH."),
    ("You", "Fine, pattern first, then ICH."),
]


def segment(index: int, speaker: str, text: str) -> dict:
    microphone = speaker == "You"
    return {
        "id": f"segment-{index:06d}",
        "epoch": 1,
        "start_seconds": (index - 1) * 12.0,
        "end_seconds": (index - 1) * 12.0 + 10.0,
        "speaker_id": "speaker-you" if microphone else "speaker-remote",
        "speaker_name": "You" if microphone else "Remote",
        "source_track": "microphone" if microphone else "system",
        "text": text,
        "confidence": None,
        "language": "en",
        "words": [],
        "overlaps_segment_ids": [],
    }


def build_transcript(lines: list[tuple[str, str]] = None, session_id: str = "01JSYNTHETIC001") -> dict:
    lines = LINES if lines is None else lines
    segments = [segment(i, speaker, text) for i, (speaker, text) in enumerate(lines, start=1)]
    return {
        "schema_version": 1,
        "session_id": session_id,
        "transcript_revision": 1,
        "created_at_utc": "2026-08-07T12:00:00+00:00",
        "source_manifest_sha256": "a" * 64,
        "duration_seconds": 600.0,
        "model": {
            "runtime": "echoforge-synthetic", "backend": "written-by-hand", "model_id": "none",
            "revision": "none", "compute_type": "none", "recognizes_speech": False,
            "worker_version": "0.1.0",
        },
        "epochs": [{"index": 1, "start_seconds": 0.0, "end_seconds": 600.0}],
        "speakers": [
            {"id": "speaker-you", "name": "You", "source_track": "microphone"},
            {"id": "speaker-remote", "name": "Remote", "source_track": "system"},
        ],
        "languages": [{"source_track": "microphone", "code": "en", "probability": None}],
        "segments": segments,
    }


def build_corpus(transcript_digest: str, short_digest: str, work_digest: str) -> dict:
    return {
        "schema_version": 1,
        "corpus_id": "synthetic-v1",
        "kind": "synthetic",
        "created_utc": "2026-08-07T00:00:00+00:00",
        "notes": (
            "Written by hand to test the scorer. Not a recording, not annotated by anyone, and not "
            "evidence about any model's summary quality. Regenerate with scripts/make-synthetic-corpus.py."
        ),
        "match_threshold": 0.5,
        "meetings": [
            {
                "meeting_id": "synthetic-001",
                "meeting_date": "2026-08-07",
                "transcript_path": "transcripts/synthetic-001.json",
                "transcript_sha256": transcript_digest,
                "transcript_fidelity": "human_corrected",
                "synthetic": True,
                "annotator": "generated by scripts/make-synthetic-corpus.py",
                "notes": "Exercises a reversal, a named owner, a deliberate unknown, and a deferred topic.",
                "gold": {
                    "decisions": [
                        {
                            "id": "d1",
                            "text": "Ship the beta on Friday",
                            "evidence": ["segment-000002", "segment-000003"],
                            "aliases": [
                                "We will ship the beta on Friday",
                                "The beta ships on Friday",
                                "The beta will be shipped on Friday",
                                "The beta was agreed to be shipped on Friday",
                                "Beta release scheduled for Friday",
                            ],
                        },
                        {
                            "id": "d2",
                            "text": "Ship the beta on Monday instead",
                            "evidence": ["segment-000008"],
                            "aliases": [
                                "We will ship the beta on Monday instead",
                                "The beta will be shipped on Monday",
                                "The beta ships on Monday instead of Friday",
                                "Beta release moved to Monday",
                            ],
                            "notes": "Reverses d1. Both must survive; keeping only one hides that the meeting changed its mind.",
                        },
                    ],
                    "action_items": [
                        {
                            "id": "a1",
                            "task": "Prepare the release notes",
                            "evidence": ["segment-000004"],
                            "aliases": [
                                "Alex will prepare the release notes by 2026-08-14",
                                "Alex will prepare the release notes",
                                "Prepare the release notes by 2026-08-14",
                            ],
                            "owner": "Alex",
                            "owner_status": "explicit",
                            "due_date": "2026-08-14",
                            "due_date_status": "explicit",
                        },
                        {
                            "id": "a2",
                            "task": "Write up the migration guide",
                            "evidence": ["segment-000006"],
                            "aliases": [
                                "Someone will have to write up the migration guide",
                                "Write the migration guide",
                                "The migration guide needs to be written up",
                                "Migration guide still needs an owner",
                            ],
                            "owner": None,
                            "owner_status": "unknown",
                            "due_date": None,
                            "due_date_status": "unknown",
                            "notes": (
                                "Nobody was assigned. An owner here is an invented commitment, and 'Someone' "
                                "is not a name."
                            ),
                        },
                    ],
                    "key_points": [
                        {
                            "id": "k1",
                            "text": "The release date was the subject of the meeting",
                            "evidence": ["segment-000001"],
                            "aliases": [
                                "The meeting was called to settle the release date",
                                "The release date was discussed",
                                "Discussion about the release date for the beta",
                            ],
                        }
                    ],
                    "open_questions": [
                        {
                            "id": "q1",
                            "text": "Who will handle the migration guide?",
                            "evidence": ["segment-000005"],
                            "aliases": ["Who is going to handle the migration guide?"],
                        },
                        {
                            "id": "q2",
                            "text": "Whether to raise the price to ninety-nine dollars",
                            "evidence": ["segment-000009", "segment-000010"],
                            "notes": "Discussed and explicitly deferred. A summary that emits this as a decision is wrong.",
                        },
                    ],
                    "risks": [
                        {
                            "id": "r1",
                            "text": "The vendor has not confirmed the certificate",
                            "evidence": ["segment-000011"],
                        }
                    ],
                    "blockers": [
                        {
                            "id": "b1",
                            "text": "Blocked on the vendor's sandbox",
                            "evidence": ["segment-000012"],
                        }
                    ],
                    "contradictions": [
                        {
                            "id": "c1",
                            "item_ids": ["d1", "d2"],
                            "notes": "Friday was decided and then reversed to Monday.",
                        }
                    ],
                },
            },
            {
                "meeting_id": "synthetic-002-short-test",
                "meeting_date": "2026-08-07",
                "transcript_path": "transcripts/synthetic-002-short-test.json",
                "transcript_sha256": short_digest,
                "transcript_fidelity": "human_corrected",
                "synthetic": True,
                "annotator": "generated by scripts/make-synthetic-corpus.py",
                "notes": (
                    "A short recorder test that assigns nothing. The correct brief has an empty "
                    "action plan and says so; 'stop the recording' is an instruction about the "
                    "meeting, not work that outlives it."
                ),
                "gold": {
                    "decisions": [],
                    "action_items": [],
                    "open_questions": [],
                    "risks": [],
                    "blockers": [],
                    "brief": {
                        "action_plan": [],
                        "must_not_appear_in_plan": [
                            "stop the recording",
                            "stopping it now",
                            "can you hear me",
                            "the window seems to be getting smaller",
                            "the panel compacts itself",
                        ],
                        "expected_context": [
                            "the interface becoming more compact while recording",
                        ],
                        "must_not_invent": ["owner", "due_date"],
                    },
                },
            },
            {
                "meeting_id": "synthetic-003-work-meeting",
                "meeting_date": "2026-08-07",
                "transcript_path": "transcripts/synthetic-003-work-meeting.json",
                "transcript_sha256": work_digest,
                "transcript_fidelity": "human_corrected",
                "synthetic": True,
                "annotator": "generated by scripts/make-synthetic-corpus.py",
                "notes": (
                    "The shape a real work meeting has: a blocker that gates everything, an "
                    "immediate customer deadline, dependent work behind it, speculative ideas that "
                    "belong in the backlog, an explicit deferral, a reversal, in-meeting "
                    "instructions, and money talk that is context rather than a task."
                ),
                "gold": {
                    "decisions": [
                        {
                            "id": "d1",
                            "text": "Do the ICH lead pipeline after JR goes live",
                            "evidence": ["segment-000011"],
                            "aliases": ["ICH pipeline follows JR"],
                        },
                        {
                            "id": "d2",
                            "text": "Build the reusable integration pattern before taking on ICH",
                            "evidence": ["segment-000024"],
                            "aliases": ["Pattern first, then ICH"],
                            "notes": "Reverses d1. Both must survive.",
                        },
                    ],
                    "action_items": [
                        {
                            "id": "a1",
                            "task": "Get access to the Rebuild admin console",
                            "evidence": ["segment-000001", "segment-000002"],
                            "aliases": ["Add Storm to Rebuild", "Grant Rebuild access"],
                            "owner": "Remote",
                            "owner_status": "explicit",
                            "due_date": None,
                            "due_date_status": "unknown",
                        },
                        {
                            "id": "a2",
                            "task": "QA signup, login and onboarding before the customer demo",
                            "evidence": ["segment-000005", "segment-000006"],
                            "aliases": ["QA the signup flow before tomorrow's demo"],
                            "owner": None,
                            "owner_status": "unknown",
                            "due_date": None,
                            "due_date_status": "unknown",
                        },
                        {
                            "id": "a3",
                            "task": "Document the billing and workspace problems found during QA",
                            "evidence": ["segment-000007", "segment-000008"],
                            "aliases": ["Write down the billing issues rather than fixing them"],
                        },
                        {
                            "id": "a4",
                            "task": "Finish JR's website integration and get them live",
                            "evidence": ["segment-000009"],
                            "aliases": ["Complete the JR integration"],
                        },
                        {
                            "id": "a5",
                            "task": "Turn the JR integration into a reusable pattern",
                            "evidence": ["segment-000010", "segment-000024"],
                            "aliases": ["Write the integration up as a pattern"],
                        },
                        {
                            "id": "a6",
                            "task": "Take over the ICH website lead pipeline",
                            "evidence": ["segment-000011"],
                            "aliases": ["Take on the ICH lead pipeline"],
                        },
                    ],
                    "blockers": [
                        {
                            "id": "b1",
                            "text": "No access to the Rebuild admin console, which blocks the JR integration",
                            "evidence": ["segment-000001", "segment-000003"],
                        }
                    ],
                    "open_questions": [],
                    "risks": [],
                    "contradictions": [
                        {
                            "id": "c1",
                            "item_ids": ["d1", "d2"],
                            "notes": "The ICH ordering was stated and then corrected.",
                        }
                    ],
                    "brief": {
                        "action_plan": ["a1", "a2", "a3", "a4", "a5", "a6"],
                        "must_be_first": "a1",
                        "notes_on_order": (
                            "Access first because the meeting says the lead fields cannot be "
                            "inspected and the integration cannot be finished without it; QA next "
                            "because the demo is tomorrow."
                        ),
                        "must_not_appear_in_plan": [
                            "share the screen",
                            "scroll down",
                            "change the google ads",
                            "touch the existing google ads",
                        ],
                        "expected_backlog": [
                            "error monitoring",
                            "customer portal",
                            "automate the onboarding sequence",
                            "move the shared inbox into a helpdesk",
                        ],
                        "expected_context": [
                            "the JR contract is eleven thousand",
                            "do not disturb the Google Ads campaigns that are producing leads",
                        ],
                        "expected_other_people": ["a1"],
                    },
                },
            },
        ],
    }


def main() -> int:
    transcripts = ROOT / "transcripts"
    transcripts.mkdir(parents=True, exist_ok=True)

    written: dict[str, str] = {}
    for name, lines, session in (
        ("synthetic-001", LINES, "01JSYNTHETIC001"),
        ("synthetic-002-short-test", SHORT_TEST_LINES, "01JSYNTHETIC002"),
        ("synthetic-003-work-meeting", WORK_MEETING_LINES, "01JSYNTHETIC003"),
    ):
        payload = json.dumps(build_transcript(lines, session), indent=2) + "\n"
        # newline="" so the bytes on disk are the bytes that were hashed. Letting Python
        # translate the line endings writes a file whose digest is not the one recorded beside
        # it, and a corpus that cannot verify its own transcript is worth nothing.
        (transcripts / f"{name}.json").write_text(payload, encoding="utf-8", newline="")
        written[name] = hashlib.sha256(payload.encode("utf-8")).hexdigest()

    digest = written["synthetic-001"]
    corpus = json.dumps(
        build_corpus(digest, written["synthetic-002-short-test"], written["synthetic-003-work-meeting"]),
        indent=2,
    ) + "\n"
    (ROOT / "corpus.json").write_text(corpus, encoding="utf-8", newline="")

    print(f"transcript sha256: {digest}")
    print(f"written: {ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
